# Site settings
title: Peru Backpacking
email: dev@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Peru Backpacking. This is a personal blog. Max and Nora
  travelling in Peru februar 21th till march 22th.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Xam Blak # add your name
author-pic: avatar.jpg
about-author: Nora & Max in Peru<br/>21. Feb - 22. Mar 2019

# Contact links
email: # Add your Email address
phone: # Add your Phone number
website: # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: # Add your Github handle
twitter: # Add your Twitter handle
facebook: # Add your Facebook handle
instagram: # Add your Instagram handle
pinterest: # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: # Add your discus identifier

# Tracker -> Google Analytics
#analytics: UA-111453754-1

# Paginate
paginate: 11
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "package-lock.json", "yarn.lock", "deploy.sh", "Gemfile", "Gemfile.lock"]
